// Bundles the plugin's Luau modules into one chunk the CLI can run without
// require, so the host half can be driven against a mock Tern runtime.
// Usage: bun tools/bundle.ts <driver.luau> <out.luau> <module order...>
const fs = require('fs');
const path = require('path');

const [, , driverPath, outPath, ...order] = process.argv;
const root = path.dirname(path.resolve(driverPath)); // tools/
const lib = path.join(root, '..', 'lib');

function clean(file: string): string {
	return fs.readFileSync(file, 'utf8').replace(/^--!(strict|nonstrict)\s*\n/, '');
}

const REQUIRE = /^[ \t]*local\s+(\w+)\s*=\s*require\((['"])([^'"]+)\2\)[ \t]*\n/gm;
const norm = (target: string) => target.replace(/^\.\//, '').replace(/^lib\//, '');

const files = new Map<string, string>();
for (const name of order) {
	files.set(name, name === 'host' ? path.join(root, '..', 'host.luau') : path.join(lib, `${name}.luau`));
}

// Pass one: which name each module is required under, anywhere in the set.
const bindings = new Map<string, string>();
for (const [, p] of files) {
	const src = clean(p);
	for (const m of src.matchAll(REQUIRE)) {
		const target = norm(m[3]);
		if (!bindings.has(target)) bindings.set(target, m[1]);
	}
}

// Pass two: each module as an immediately-called function, its requires
// rebound to the bundle's names.
const chunks: string[] = [];
for (const name of order) {
	let src = clean(files.get(name)!).replace(REQUIRE, '');
	if (name === 'host') src = src.replace(/^local tern: any = _G\.tern\n/m, '');
	const varName = bindings.get(name) ?? name;
	const deps: string[] = [];
	for (const [target, depVar] of bindings) {
		if (target !== name && new RegExp(`\\b${depVar}\\b`).test(src)) {
			deps.push(`local ${depVar} = ${depVar}`);
		}
	}
	const wrapper = name === 'host'
		? `local ${varName} = (function(tern)\n${deps.length ? deps.join('\n') + '\n' : ''}${src}\nend)(tern)\n`
		: `local ${varName} = (function()\n${deps.length ? deps.join('\n') + '\n' : ''}${src}\nend)()\n`;
	chunks.push(wrapper);
}
const driverText = clean(path.resolve(driverPath));
const marker = driverText.split("local _host = require('../host')");
const parts = marker.length === 2 ? [marker[0], chunks.join('\n'), marker[1]] : [chunks.join('\n'), marker[0]];
const out = ['-- generated by tools/bundle.ts; do not edit', ...parts].join('\n');
fs.writeFileSync(path.resolve(outPath), out);
console.log(`bundled ${order.length} modules into ${outPath}`);
