// Turns the scene library JSON into a Luau data module the plugin can require.
import { readFileSync, writeFileSync } from 'node:fs';

type Entry = {
	phase: string;
	world: string;
	style: string;
	concept: string;
	source: string;
	scene: { code: string };
};
const delimiter = (code: string) => {
	for (let level = 0; level < 8; level++) {
		const eq = '='.repeat(level);
		const open = `[${eq}[`;
		// The terminator is a ] followed by the closing bracket.
		if (!code.includes(open) && !code.includes(`]${eq}]`)) {
			return { open, close: `]${eq}]` };
		}
	}
	throw new Error('no long-string delimiter fits');
};

const quote = (value: string) => {
	const { open, close } = delimiter(value);
	return open + '\n' + value + '\n' + close;
};

const escape = (value: string) =>
	'"' + value.replace(/\\/g, '\\\\').replace(/\n/g, '\\n').replace(/\r/g, '\\r').replace(/\t/g, '\\t').replace(/"/g, '\\"') + '"';

const library = JSON.parse(readFileSync('lib/scenes.json', 'utf8')) as Entry[];
const lines: string[] = [
	'-- The scene library: ready-made cartoons, one per agent phase.',
	'-- Generated by tools/make_scenes.ts from the claude-toons scene set.',
	'',
	'return {',
];

for (const entry of library) {
	lines.push(' {');
	lines.push(`  phase = ${escape(entry.phase)},`);
	lines.push(`  world = ${escape(entry.world)},`);
	lines.push(`  style = ${escape(entry.style)},`);
	lines.push(`  concept = ${escape(entry.concept)},`);
	lines.push(`  source = ${escape(entry.source)},`);
	lines.push(`  code = ${quote(entry.scene.code)},`);
	lines.push(' },');
}
lines.push('}');

writeFileSync('lib/scenes.luau', lines.join('\n') + '\n');
console.log(`wrote lib/scenes.luau with ${library.length} scenes`);
